/* Oracle. Delivery cadence for login event feed, supporting visualization describing outages for sysadmin monitoring.
*/

SELECT 
 CASE 
    WHEN DIFFERENCE_FLAG > 4 THEN DIFFERENCE_FLAG||'-minute interruption before '||HOUR_TODAY||' '||MIN_TODAY||' today.<br>'
  END AS MESSAGE
FROM(
SELECT 
--  DATEPART(hour, sysdate)
  TO_CHAR(TRUNC(SYSDATE)) AS DAY_TODAY
  ,TO_CHAR(LAST_DELIVERY_TIME,'HH24') AS HOUR_TODAY
  ,TO_CHAR(LAST_DELIVERY_TIME,'MI') AS MIN_TODAY
  ,COUNT(*) AS Submission_Totals
  ,TO_CHAR(LAST_DELIVERY_TIME,'MI')-LAG(TO_CHAR(LAST_DELIVERY_TIME,'MI')) OVER (ORDER BY TO_CHAR(LAST_DELIVERY_TIME,'HH24')) AS DIFFERENCE_FLAG
--  ,COUNT(CASE WHEN TO_CHAR(LAST_DELIVERY_TIME,'MI')-LAG(TO_CHAR(LAST_DELIVERY_TIME,'MI')) OVER (TO_CHAR(LAST_DELIVERY_TIME,'HH24')) >4 THEN 1 END) AS INTERRUPTION_COUNT
FROM bblearn.BBGS_ER_LOGINEVENTS
WHERE LAST_DELIVERY_TIME > TRUNC(SYSDATE)
AND LAST_DELIVERY_STATUS = 1
GROUP BY TO_CHAR(TRUNC(SYSDATE)),TO_CHAR(LAST_DELIVERY_TIME,'HH24'),TO_CHAR(LAST_DELIVERY_TIME,'MI')
ORDER BY TO_CHAR(TRUNC(SYSDATE)),TO_CHAR(LAST_DELIVERY_TIME,'HH24'),TO_CHAR(LAST_DELIVERY_TIME,'MI')
)
GROUP BY HOUR_TODAY, MIN_TODAY, DIFFERENCE_FLAG
;