/* Oracle. Start Prep: Term Courses Added or Modified. Supporting visualization tool for system admins monitoring automated course creation processes.
*/

SELECT 
  'The Courses DSK <b>'||TERM_COURSE_DSK||'</b><ul><li> Was modified on '||TERM_COURSE_MODIFIED||'.</li><li>'||ENABLED_COUNT||' courses are ENABLED/AVAILABLE in the DSK.</li><li>'||DISABLED_COUNT||' courses are DISABLED in the DSK.</li><li>'||UNAVAILABLE_COUNT||' courses are UNAVAILABLE in the DSK.</li></ul><br>' AS MESSAGE,BATCH_COUNT AS THE_COUNT
FROM
(SELECT 
  DS.DTMODIFIED AS TERM_COURSE_MODIFIED
  ,DS.BATCH_UID AS TERM_COURSE_DSK
  ,COUNT(DS.BATCH_UID) AS BATCH_COUNT
  ,COUNT(CASE WHEN (CM.ROW_STATUS=0 AND CM.AVAILABLE_IND='Y') THEN 1 END) AS ENABLED_COUNT
  ,COUNT(CASE WHEN CM.ROW_STATUS=2 THEN 1 END) AS DISABLED_COUNT
  ,COUNT(CASE WHEN CM.AVAILABLE_IND='N' THEN 1 END) AS UNAVAILABLE_COUNT
FROM bblearn.data_source DS
INNER JOIN bblearn.COURSE_MAIN CM
  ON DS.PK1=CM.DATA_SRC_PK1
WHERE DS.DTMODIFIED > sysdate-15
AND DS.BATCH_UID LIKE 'COURSES_%'
GROUP BY DS.DTMODIFIED, DS.BATCH_UID, CM.ROW_STATUS,CM.AVAILABLE_IND
ORDER BY DS.DTMODIFIED DESC, DS.BATCH_UID, CM.ROW_STATUS,CM.AVAILABLE_IND ASC)